'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RCDIY2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Import Keyboard Data From RCT File 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property btnImportKeyboard() As String
            Get
                Return ResourceManager.GetString("btnImportKeyboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 从RCT文件导入键盘数据 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property btnImportKeyboard_cn() As String
            Get
                Return ResourceManager.GetString("btnImportKeyboard_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 1986 Enable 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckb1986Enable() As String
            Get
                Return ResourceManager.GetString("ckb1986Enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 1986码使能 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckb1986Enable_cn() As String
            Get
                Return ResourceManager.GetString("ckb1986Enable_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bit1=1, if data1&lt;=0x3F Bit1=0, if data1&gt;0x3F 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBit1Option() As String
            Get
                Return ResourceManager.GetString("ckbBit1Option", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 如果data1&lt;=0x3F, 则Bit1=1 如果data1&gt;0x3F,  则Bit1=0 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBit1Option_cn() As String
            Get
                Return ResourceManager.GetString("ckbBit1Option_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bit Expand 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBitExpand() As String
            Get
                Return ResourceManager.GetString("ckbBitExpand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 位宽度扩展 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBitExpand_cn() As String
            Get
                Return ResourceManager.GetString("ckbBitExpand_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 With Boot Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBootCode() As String
            Get
                Return ResourceManager.GetString("ckbBootCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 有引导码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbBootCode_cn() As String
            Get
                Return ResourceManager.GetString("ckbBootCode_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 1 revert 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbData1Revert() As String
            Get
                Return ResourceManager.GetString("ckbData1Revert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复码输出数据码1交替取反 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbData1Revert_cn() As String
            Get
                Return ResourceManager.GetString("ckbData1Revert_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 2 revert 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbData2Revert() As String
            Get
                Return ResourceManager.GetString("ckbData2Revert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复码输出数据码2交替取反 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbData2Revert_cn() As String
            Get
                Return ResourceManager.GetString("ckbData2Revert_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Double Frame Mode 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbDoubleFrame() As String
            Get
                Return ResourceManager.GetString("ckbDoubleFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 双帧发送模式 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbDoubleFrame_cn() As String
            Get
                Return ResourceManager.GetString("ckbDoubleFrame_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LC7464 Check 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbL7464Check() As String
            Get
                Return ResourceManager.GetString("ckbL7464Check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LC7464校验 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbL7464Check_cn() As String
            Get
                Return ResourceManager.GetString("ckbL7464Check_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Multi User Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbMultiUser() As String
            Get
                Return ResourceManager.GetString("ckbMultiUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 多用户码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbMultiUser_cn() As String
            Get
                Return ResourceManager.GetString("ckbMultiUser_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Repeat Data Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRepeatDataFrame() As String
            Get
                Return ResourceManager.GetString("ckbRepeatDataFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复数据帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRepeatDataFrame_cn() As String
            Get
                Return ResourceManager.GetString("ckbRepeatDataFrame_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Repeat Mode Group 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRepeatModeGroup() As String
            Get
                Return ResourceManager.GetString("ckbRepeatModeGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复码模式分组 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRepeatModeGroup_cn() As String
            Get
                Return ResourceManager.GetString("ckbRepeatModeGroup_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 With Revert Bit (Later 16 bits) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRevertBitHi() As String
            Get
                Return ResourceManager.GetString("ckbRevertBitHi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 后16位有反转位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRevertBitHi_cn() As String
            Get
                Return ResourceManager.GetString("ckbRevertBitHi_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 With Revert Bit (Previous 16 bits) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRevertBitLo() As String
            Get
                Return ResourceManager.GetString("ckbRevertBitLo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 前16位有反转位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbRevertBitLo_cn() As String
            Get
                Return ResourceManager.GetString("ckbRevertBitLo_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Up Key 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbUpKeyEnable() As String
            Get
                Return ResourceManager.GetString("ckbUpKeyEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 抬手码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbUpKeyEnable_cn() As String
            Get
                Return ResourceManager.GetString("ckbUpKeyEnable_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Code 2 revert 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbUser2Revert() As String
            Get
                Return ResourceManager.GetString("ckbUser2Revert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复码输出用户码2交替取反 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbUser2Revert_cn() As String
            Get
                Return ResourceManager.GetString("ckbUser2Revert_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VDD Key Scan 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbVDDKeyScan() As String
            Get
                Return ResourceManager.GetString("ckbVDDKeyScan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VDD允许键扫描 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ckbVDDKeyScan_cn() As String
            Get
                Return ResourceManager.GetString("ckbVDDKeyScan_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpBoot() As String
            Get
                Return ResourceManager.GetString("grpBoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 引导帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpBoot_cn() As String
            Get
                Return ResourceManager.GetString("grpBoot_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Carrier Option 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpCarrier() As String
            Get
                Return ResourceManager.GetString("grpCarrier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 载波设置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpCarrier_cn() As String
            Get
                Return ResourceManager.GetString("grpCarrier_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Send Direction 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpDataDir() As String
            Get
                Return ResourceManager.GetString("grpDataDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据发送方向 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpDataDir_cn() As String
            Get
                Return ResourceManager.GetString("grpDataDir_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpDataFrame() As String
            Get
                Return ResourceManager.GetString("grpDataFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpDataFrame_cn() As String
            Get
                Return ResourceManager.GetString("grpDataFrame_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Global Format Option 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpGlobal() As String
            Get
                Return ResourceManager.GetString("grpGlobal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 通用编码属性 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpGlobal_cn() As String
            Get
                Return ResourceManager.GetString("grpGlobal_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IROUT Drive 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpIROUT() As String
            Get
                Return ResourceManager.GetString("grpIROUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IROUT驱动 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpIROUT_cn() As String
            Get
                Return ResourceManager.GetString("grpIROUT_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Key Option 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpKey() As String
            Get
                Return ResourceManager.GetString("grpKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 按键选项 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpKey_cn() As String
            Get
                Return ResourceManager.GetString("grpKey_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LED Drive 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLED() As String
            Get
                Return ResourceManager.GetString("grpLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LED驱动 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLED_cn() As String
            Get
                Return ResourceManager.GetString("grpLED_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logic 0 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLogic0() As String
            Get
                Return ResourceManager.GetString("grpLogic0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 逻辑0设置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLogic0_cn() As String
            Get
                Return ResourceManager.GetString("grpLogic0_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logic 1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLogic1() As String
            Get
                Return ResourceManager.GetString("grpLogic1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 逻辑1设置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpLogic1_cn() As String
            Get
                Return ResourceManager.GetString("grpLogic1_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Others 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpOthers() As String
            Get
                Return ResourceManager.GetString("grpOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 其他 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property grpOthers_cn() As String
            Get
                Return ResourceManager.GetString("grpOthers_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bit1 Option 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblBit1Option() As String
            Get
                Return ResourceManager.GetString("lblBit1Option", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bit1选项 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblBit1Option_cn() As String
            Get
                Return ResourceManager.GetString("lblBit1Option_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Carrier Freq.(KHz) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblCarrierFreq() As String
            Get
                Return ResourceManager.GetString("lblCarrierFreq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 载波频率(KHz) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblCarrierFreq_cn() As String
            Get
                Return ResourceManager.GetString("lblCarrierFreq_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Checksum 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblChecksum() As String
            Get
                Return ResourceManager.GetString("lblChecksum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 校验和值 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblChecksum_cn() As String
            Get
                Return ResourceManager.GetString("lblChecksum_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblData2Code() As String
            Get
                Return ResourceManager.GetString("lblData2Code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据码2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblData2Code_cn() As String
            Get
                Return ResourceManager.GetString("lblData2Code_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bits 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDataCode1Bits() As String
            Get
                Return ResourceManager.GetString("lblDataCode1Bits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 位数 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDataCode1Bits_cn() As String
            Get
                Return ResourceManager.GetString("lblDataCode1Bits_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Debounce Time (ms) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDebounce() As String
            Get
                Return ResourceManager.GetString("lblDebounce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 按键去抖时间(ms) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDebounce_cn() As String
            Get
                Return ResourceManager.GetString("lblDebounce_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Duty 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDuty() As String
            Get
                Return ResourceManager.GetString("lblDuty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 载波占空比 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblDuty_cn() As String
            Get
                Return ResourceManager.GetString("lblDuty_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid Key Code(HEX) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblInvalidKey() As String
            Get
                Return ResourceManager.GetString("lblInvalidKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无效按键编码(HEX) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblInvalidKey_cn() As String
            Get
                Return ResourceManager.GetString("lblInvalidKey_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IROUT Current 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblIRCurrent() As String
            Get
                Return ResourceManager.GetString("lblIRCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IROUT驱动电流 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblIRCurrent_cn() As String
            Get
                Return ResourceManager.GetString("lblIRCurrent_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LIMIT Count of Frame while key pressed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblKeyRemain() As String
            Get
                Return ResourceManager.GetString("lblKeyRemain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 限制按键持续发码帧数 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblKeyRemain_cn() As String
            Get
                Return ResourceManager.GetString("lblKeyRemain_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LED Current 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLEDCurrent() As String
            Get
                Return ResourceManager.GetString("lblLEDCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LED驱动电流 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLEDCurrent_cn() As String
            Get
                Return ResourceManager.GetString("lblLEDCurrent_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Level High(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLevelHigh() As String
            Get
                Return ResourceManager.GetString("lblLevelHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高电平时间(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLevelHigh_cn() As String
            Get
                Return ResourceManager.GetString("lblLevelHigh_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Level Low(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLevelLow() As String
            Get
                Return ResourceManager.GetString("lblLevelLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 低电平时间(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblLevelLow_cn() As String
            Get
                Return ResourceManager.GetString("lblLevelLow_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblMultiUserCode() As String
            Get
                Return ResourceManager.GetString("lblMultiUserCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 码值 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblMultiUserCode_cn() As String
            Get
                Return ResourceManager.GetString("lblMultiUserCode_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Position 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblPosition() As String
            Get
                Return ResourceManager.GetString("lblPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 位置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblPosition_cn() As String
            Get
                Return ResourceManager.GetString("lblPosition_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pullup Res 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblPURes() As String
            Get
                Return ResourceManager.GetString("lblPURes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上拉电阻 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblPURes_cn() As String
            Get
                Return ResourceManager.GetString("lblPURes_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Range I 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeI() As String
            Get
                Return ResourceManager.GetString("lblRangeI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 区域I 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeI_cn() As String
            Get
                Return ResourceManager.GetString("lblRangeI_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Range II 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeII() As String
            Get
                Return ResourceManager.GetString("lblRangeII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 区域II 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeII_cn() As String
            Get
                Return ResourceManager.GetString("lblRangeII_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Range III 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeIII() As String
            Get
                Return ResourceManager.GetString("lblRangeIII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 区域III 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRangeIII_cn() As String
            Get
                Return ResourceManager.GetString("lblRangeIII_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Group A 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatGroupA() As String
            Get
                Return ResourceManager.GetString("lblRepeatGroupA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 A组 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatGroupA_cn() As String
            Get
                Return ResourceManager.GetString("lblRepeatGroupA_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Group B 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatGroupB() As String
            Get
                Return ResourceManager.GetString("lblRepeatGroupB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 B组 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatGroupB_cn() As String
            Get
                Return ResourceManager.GetString("lblRepeatGroupB_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Repeat Stop Time (us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatStopTime() As String
            Get
                Return ResourceManager.GetString("lblRepeatStopTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复帧停止时间(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblRepeatStopTime_cn() As String
            Get
                Return ResourceManager.GetString("lblRepeatStopTime_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Scan Interval 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblScanInterval() As String
            Get
                Return ResourceManager.GetString("lblScanInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 按键扫描间隔 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblScanInterval_cn() As String
            Get
                Return ResourceManager.GetString("lblScanInterval_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Time (us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblStopTime() As String
            Get
                Return ResourceManager.GetString("lblStopTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 停止时间(us) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblStopTime_cn() As String
            Get
                Return ResourceManager.GetString("lblStopTime_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bits 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblUserBits() As String
            Get
                Return ResourceManager.GetString("lblUserBits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 位数 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblUserBits_cn() As String
            Get
                Return ResourceManager.GetString("lblUserBits_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblUserCode() As String
            Get
                Return ResourceManager.GetString("lblUserCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property lblUserCode_cn() As String
            Get
                Return ResourceManager.GetString("lblUserCode_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;File 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFile() As String
            Get
                Return ResourceManager.GetString("mnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文件(&amp;F) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFile_cn() As String
            Get
                Return ResourceManager.GetString("mnuFile_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 E&amp;xit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileExit() As String
            Get
                Return ResourceManager.GetString("mnuFileExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 退出(&amp;X) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileExit_cn() As String
            Get
                Return ResourceManager.GetString("mnuFileExit_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;New 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileNew() As String
            Get
                Return ResourceManager.GetString("mnuFileNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建(&amp;N) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileNew_cn() As String
            Get
                Return ResourceManager.GetString("mnuFileNew_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Open 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileOpen() As String
            Get
                Return ResourceManager.GetString("mnuFileOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打开(&amp;O) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileOpen_cn() As String
            Get
                Return ResourceManager.GetString("mnuFileOpen_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Save 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileSave() As String
            Get
                Return ResourceManager.GetString("mnuFileSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 保存(&amp;S) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileSave_cn() As String
            Get
                Return ResourceManager.GetString("mnuFileSave_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save &amp;As ... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileSaveAs() As String
            Get
                Return ResourceManager.GetString("mnuFileSaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 另存为(&amp;A) ... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuFileSaveAs_cn() As String
            Get
                Return ResourceManager.GetString("mnuFileSaveAs_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Help 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuHelp() As String
            Get
                Return ResourceManager.GetString("mnuHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 帮助(H) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuHelp_cn() As String
            Get
                Return ResourceManager.GetString("mnuHelp_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 About 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuHelpAbout() As String
            Get
                Return ResourceManager.GetString("mnuHelpAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关于 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuHelpAbout_cn() As String
            Get
                Return ResourceManager.GetString("mnuHelpAbout_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Chinese 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLangChinese() As String
            Get
                Return ResourceManager.GetString("mnuLangChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 简体中文(&amp;C) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLangChinese_cn() As String
            Get
                Return ResourceManager.GetString("mnuLangChinese_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;English 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLangEnglish() As String
            Get
                Return ResourceManager.GetString("mnuLangEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 英语(&amp;E) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLangEnglish_cn() As String
            Get
                Return ResourceManager.GetString("mnuLangEnglish_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Language 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLanguage() As String
            Get
                Return ResourceManager.GetString("mnuLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 语言(&amp;L) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuLanguage_cn() As String
            Get
                Return ResourceManager.GetString("mnuLanguage_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Tool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuTool() As String
            Get
                Return ResourceManager.GetString("mnuTool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 工具(&amp;T) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuTool_cn() As String
            Get
                Return ResourceManager.GetString("mnuTool_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export to S19 File 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolExportS19() As String
            Get
                Return ResourceManager.GetString("mnuToolExportS19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导出S19文件 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolExportS19_cn() As String
            Get
                Return ResourceManager.GetString("mnuToolExportS19_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Import Keyboard 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolImportKeyboard() As String
            Get
                Return ResourceManager.GetString("mnuToolImportKeyboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导入键盘数据 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolImportKeyboard_cn() As String
            Get
                Return ResourceManager.GetString("mnuToolImportKeyboard_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Import from S19 File 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolImportS19() As String
            Get
                Return ResourceManager.GetString("mnuToolImportS19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导入S19文件 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuToolImportS19_cn() As String
            Get
                Return ResourceManager.GetString("mnuToolImportS19_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Wave 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuWave() As String
            Get
                Return ResourceManager.GetString("mnuWave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 波形(&amp;W) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mnuWave_cn() As String
            Get
                Return ResourceManager.GetString("mnuWave_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 8-bit Checksum 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radChecksum() As String
            Get
                Return ResourceManager.GetString("radChecksum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 8位校验和 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radChecksum_cn() As String
            Get
                Return ResourceManager.GetString("radChecksum_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compact Repeat 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radCompact() As String
            Get
                Return ResourceManager.GetString("radCompact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 简单重复码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radCompact_cn() As String
            Get
                Return ResourceManager.GetString("radCompact_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Complete Repeat 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radComplete() As String
            Get
                Return ResourceManager.GetString("radComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 完全重复码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radComplete_cn() As String
            Get
                Return ResourceManager.GetString("radComplete_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 1 no change 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radData1Repeat() As String
            Get
                Return ResourceManager.GetString("radData1Repeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复码输出数据码1的原码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radData1Repeat_cn() As String
            Get
                Return ResourceManager.GetString("radData1Repeat_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Changeless Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radData2Changeless() As String
            Get
                Return ResourceManager.GetString("radData2Changeless", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 固定码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radData2Changeless_cn() As String
            Get
                Return ResourceManager.GetString("radData2Changeless_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Define Stop Time 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radDefineStopTime() As String
            Get
                Return ResourceManager.GetString("radDefineStopTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 定义停止时间 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radDefineStopTime_cn() As String
            Get
                Return ResourceManager.GetString("radDefineStopTime_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Define Whole Frame Time 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radDefineWholeFrame() As String
            Get
                Return ResourceManager.GetString("radDefineWholeFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 定义完整帧时间 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radDefineWholeFrame_cn() As String
            Get
                Return ResourceManager.GetString("radDefineWholeFrame_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High Bit First 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHighBitFirst() As String
            Get
                Return ResourceManager.GetString("radHighBitFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先高位后低位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHighBitFirst_cn() As String
            Get
                Return ResourceManager.GetString("radHighBitFirst_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High to Low 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHighToLow() As String
            Get
                Return ResourceManager.GetString("radHighToLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先高后低 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHighToLow_cn() As String
            Get
                Return ResourceManager.GetString("radHighToLow_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High + Low + Stop Bit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL0() As String
            Get
                Return ResourceManager.GetString("radHL0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高电平 + 低电平 + 停止位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL0_cn() As String
            Get
                Return ResourceManager.GetString("radHL0_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High + Low + 0 + Stop Bit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL01() As String
            Get
                Return ResourceManager.GetString("radHL01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高电平 + 低电平 + 0 + 停止位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL01_cn() As String
            Get
                Return ResourceManager.GetString("radHL01_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High + Low + 1 + Stop Bit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL11() As String
            Get
                Return ResourceManager.GetString("radHL11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高电平 + 低电平 + 1 + 停止位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHL11_cn() As String
            Get
                Return ResourceManager.GetString("radHL11_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High to Low 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHtoL_Stop() As String
            Get
                Return ResourceManager.GetString("radHtoL_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先高电平后低电平 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radHtoL_Stop_cn() As String
            Get
                Return ResourceManager.GetString("radHtoL_Stop_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SUM 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radL7464_Sum() As String
            Get
                Return ResourceManager.GetString("radL7464_Sum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 求和 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radL7464_Sum_cn() As String
            Get
                Return ResourceManager.GetString("radL7464_Sum_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XOR 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radL7464_Xor() As String
            Get
                Return ResourceManager.GetString("radL7464_Xor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 异或 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radL7464_Xor_cn() As String
            Get
                Return ResourceManager.GetString("radL7464_Xor_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Active High 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLEDHi() As String
            Get
                Return ResourceManager.GetString("radLEDHi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高电平有效 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLEDHi_cn() As String
            Get
                Return ResourceManager.GetString("radLEDHi_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Active Low 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLEDLo() As String
            Get
                Return ResourceManager.GetString("radLEDLo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 低电平有效 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLEDLo_cn() As String
            Get
                Return ResourceManager.GetString("radLEDLo_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Low Bit First 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLowBitFirst() As String
            Get
                Return ResourceManager.GetString("radLowBitFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先低位后高位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLowBitFirst_cn() As String
            Get
                Return ResourceManager.GetString("radLowBitFirst_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Low to High 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLowToHigh() As String
            Get
                Return ResourceManager.GetString("radLowToHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先低后高 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLowToHigh_cn() As String
            Get
                Return ResourceManager.GetString("radLowToHigh_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Low to High 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLtoH_Stop() As String
            Get
                Return ResourceManager.GetString("radLtoH_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 先低电平后高电平 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radLtoH_Stop_cn() As String
            Get
                Return ResourceManager.GetString("radLtoH_Stop_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Revert Data Code 1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radRevertCode1() As String
            Get
                Return ResourceManager.GetString("radRevertCode1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据码1的反码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radRevertCode1_cn() As String
            Get
                Return ResourceManager.GetString("radRevertCode1_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 H/L Time Same as Boot 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radSameAsBoot() As String
            Get
                Return ResourceManager.GetString("radSameAsBoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高低电平设置同简单引导帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radSameAsBoot_cn() As String
            Get
                Return ResourceManager.GetString("radSameAsBoot_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 H/L Time Same as Compact 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radSameAsCompact() As String
            Get
                Return ResourceManager.GetString("radSameAsCompact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高低电平设置同简单重复码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radSameAsCompact_cn() As String
            Get
                Return ResourceManager.GetString("radSameAsCompact_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Scan Key Continuously 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radScanCont() As String
            Get
                Return ResourceManager.GetString("radScanCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 结束码期间按键持续扫描 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radScanCont_cn() As String
            Get
                Return ResourceManager.GetString("radScanCont_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Scan Key One Time 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radScanOneTime() As String
            Get
                Return ResourceManager.GetString("radScanOneTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 结束码期间按键扫描1次 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property radScanOneTime_cn() As String
            Get
                Return ResourceManager.GetString("radScanOneTime_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Frame Configration 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabFrame() As String
            Get
                Return ResourceManager.GetString("tabFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 发码帧配置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabFrame_cn() As String
            Get
                Return ResourceManager.GetString("tabFrame_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Format Setting 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting0() As String
            Get
                Return ResourceManager.GetString("tabSetting0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 格式设置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting0_cn() As String
            Get
                Return ResourceManager.GetString("tabSetting0_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Key Setting 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting1() As String
            Get
                Return ResourceManager.GetString("tabSetting1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 按键设置 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting1_cn() As String
            Get
                Return ResourceManager.GetString("tabSetting1_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting2() As String
            Get
                Return ResourceManager.GetString("tabSetting2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 信息 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tabSetting2_cn() As String
            Get
                Return ResourceManager.GetString("tabSetting2_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remote Controller DIY2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 遥控器DIY 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Title_cn() As String
            Get
                Return ResourceManager.GetString("Title_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolFit() As String
            Get
                Return ResourceManager.GetString("tolFit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 显示全部 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolFit_cn() As String
            Get
                Return ResourceManager.GetString("tolFit_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Zoom In 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolZoomIn() As String
            Get
                Return ResourceManager.GetString("tolZoomIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 放大 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolZoomIn_cn() As String
            Get
                Return ResourceManager.GetString("tolZoomIn_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Zoom Out  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolZoomOut() As String
            Get
                Return ResourceManager.GetString("tolZoomOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 缩小 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tolZoomOut_cn() As String
            Get
                Return ResourceManager.GetString("tolZoomOut_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameBoot() As String
            Get
                Return ResourceManager.GetString("trvFrameBoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 引导帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameBoot_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameBoot_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compact Repeat Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameCompactRepeat() As String
            Get
                Return ResourceManager.GetString("trvFrameCompactRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 简单重复码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameCompactRepeat_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameCompactRepeat_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Complete Repeat Code 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameCompleteRepeat() As String
            Get
                Return ResourceManager.GetString("trvFrameCompleteRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 完全重复码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameCompleteRepeat_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameCompleteRepeat_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameData() As String
            Get
                Return ResourceManager.GetString("trvFrameData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameData_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameData_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameDataCode1() As String
            Get
                Return ResourceManager.GetString("trvFrameDataCode1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据码1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameDataCode1_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameDataCode1_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Code 2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameDataCode2() As String
            Get
                Return ResourceManager.GetString("trvFrameDataCode2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 数据码2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameDataCode2_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameDataCode2_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Repeat Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameRepeat() As String
            Get
                Return ResourceManager.GetString("trvFrameRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重复帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameRepeat_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameRepeat_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Split Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameSplit() As String
            Get
                Return ResourceManager.GetString("trvFrameSplit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 分割帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameSplit_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameSplit_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStop() As String
            Get
                Return ResourceManager.GetString("trvFrameStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 结束帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStop_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameStop_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Bit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStopBit() As String
            Get
                Return ResourceManager.GetString("trvFrameStopBit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 停止位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStopBit_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameStopBit_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Time 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStopCode() As String
            Get
                Return ResourceManager.GetString("trvFrameStopCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 停止码 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameStopCode_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameStopCode_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Frame 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameUser() As String
            Get
                Return ResourceManager.GetString("trvFrameUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户帧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameUser_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameUser_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Code 2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameUserCode2() As String
            Get
                Return ResourceManager.GetString("trvFrameUserCode2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户码2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property trvFrameUserCode2_cn() As String
            Get
                Return ResourceManager.GetString("trvFrameUserCode2_cn", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
